name: Run Trading Bot 

on: 
  schedule:  # Trigger on a schedule
    - cron: '30 8-15 * * 1-5'  # Your desired schedule 

jobs:
  run_script:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - uses: actions/checkout@v3  # Check out your repository code

      - name: Set up Python 
        uses: actions/setup-python@v4 
        with:
          python-version: '3.x'  
          architecture: 'x64'  

      - name: Install dependencies
        run: pip install alpaca_trade_api pandas pandas-ta cronitor 

      - name: Run the script
        run: python OrderLoop.py 
